In [1]:
import cv2
import numpy
import pandas
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from skimage import io
from PIL import Image
import os
import matplotlib.patches as mpatch

In [2]:
os.makedirs("append-cluster", exist_ok=True)
os.makedirs("append-cluster/image_after")
os.makedirs("append-cluster/image_after/5")

In [3]:
os.makedirs("append-cluster/data_after/5", exist_ok=True)

In [4]:
def Kmeans_color_segment(image_path, n, x, z):
    image=io.imread(image_path)
    # image_after=cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image_after=image
    
    pixel_data = image_after.reshape((-1, 3))
    pixel_data = numpy.float32(pixel_data)
    
    kmeans = KMeans(n_clusters=n, random_state=None, init='k-means++', n_init='auto')
    kmeans.fit(pixel_data)
    
    labels = kmeans.labels_
    centers = numpy.uint8(kmeans.cluster_centers_)
    segmented_image = centers[labels].reshape(image_after.shape)
    cluster_areas = {i: numpy.sum(labels == i) for i in range(n)}
    
    plt.figure(figsize=(10, 5))
    plt.subplot(1, 2, 1)
    plt.imshow(cv2.cvtColor(image_after, cv2.COLOR_BGR2RGB))
    plt.title('Original Image')
    plt.legend()
    
    plt.subplot(1, 2, 2)
    plt.imshow(cv2.cvtColor(segmented_image, cv2.COLOR_BGR2RGB))
    plt.title('Segmented Image (KMeans)')
    plt.savefig(f"append-cluster/image_after/5/img-{x}-retouched-{z}.jpg")
    plt.close()
    
    print("각 클러스터의 면적(픽셀 수):", cluster_areas)
    print("클러스터 중심 색상 (RGB):", centers)
    
    data = {'cluster_id': [], 'rgb_color': [], 'area_pixels': []}
    
    for i in range(n):
        data['cluster_id'].append(f'Cluster {i}')
        data['rgb_color'].append(tuple(centers[i]))
        data['area_pixels'].append(cluster_areas[i])
        
    df = pandas.DataFrame(data)
    df.to_csv(f"append-cluster/data_after/5/retouched-data-{x}-{z}.csv", index=False)
    print(f"클러스터 면적 정보가 저장되었습니다.")
    
    return cluster_areas, segmented_image

In [5]:
for i in range(1, 6):
    Kmeans_color_segment(f"img/img-resized/img-{i}-resized.jpg", 5, i, 5)

C:\Users\katia\AppData\Local\Temp\ipykernel_25312\3295064861.py:21: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(2438994), 1: np.int64(2123556), 2: np.int64(2457464), 3: np.int64(1880333), 4: np.int64(1339653)}
클러스터 중심 색상 (RGB): [[123 148  61]
 [ 79  95  37]
 [167 201  68]
 [ 30  36   9]
 [197 215 137]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_25312\3295064861.py:21: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(3568793), 1: np.int64(1926948), 2: np.int64(1201729), 3: np.int64(1454312), 4: np.int64(2088218)}
클러스터 중심 색상 (RGB): [[165 188 150]
 [ 95 103  68]
 [157 186  82]
 [ 54  58  37]
 [124 142 111]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_25312\3295064861.py:21: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(2248092), 1: np.int64(2369653), 2: np.int64(2058806), 3: np.int64(1369717), 4: np.int64(2193732)}
클러스터 중심 색상 (RGB): [[ 79  86  60]
 [ 36  42  22]
 [169 186 118]
 [211 224 165]
 [125 137  89]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_25312\3295064861.py:21: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(2534050), 1: np.int64(2425235), 2: np.int64(2189888), 3: np.int64(1227991), 4: np.int64(1862836)}
클러스터 중심 색상 (RGB): [[ 88 104  37]
 [127 148  76]
 [182 198  60]
 [193 206 149]
 [ 39  42  15]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_25312\3295064861.py:21: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(3178940), 1: np.int64(1206163), 2: np.int64(1960878), 3: np.int64(1349957), 4: np.int64(2544062)}
클러스터 중심 색상 (RGB): [[ 95  94  83]
 [200 207  90]
 [ 51  48  36]
 [207 205 160]
 [143 152 106]]
클러스터 면적 정보가 저장되었습니다.
