In [9]:
import cv2
import numpy
import pandas
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from skimage import io
from PIL import Image
import os

In [10]:
import matplotlib.patches as mpatch

In [11]:
os.makedirs("img/img-retouched", exist_ok=True)
for i in range(1, 6):
    os.makedirs(f"img/img-retouched/img-{i}-retouched", exist_ok=True)

In [12]:
os.makedirs("retouched-data", exist_ok=True)

In [13]:
def Kmeans_color_segment(image_path, n, x, z):
    image=io.imread(image_path)
    image_after=cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    
    pixel_data = image_after.reshape((-1, 3))
    pixel_data = numpy.float32(pixel_data)
    
    kmeans = KMeans(n_clusters=n, random_state=None, init='k-means++', n_init='auto')
    kmeans.fit(pixel_data)
    
    labels = kmeans.labels_
    centers = numpy.uint8(kmeans.cluster_centers_)
    segmented_image = centers[labels].reshape(image_after.shape)
    cluster_areas = {i: numpy.sum(labels == i) for i in range(n)}
    
    plt.figure(figsize=(10, 5))
    plt.subplot(1, 2, 1)
    plt.imshow(cv2.cvtColor(image_after, cv2.COLOR_BGR2RGB))
    plt.title('Original Image')
    plt.legend()
    
    plt.subplot(1, 2, 2)
    plt.imshow(cv2.cvtColor(segmented_image, cv2.COLOR_BGR2RGB))
    plt.title('Segmented Image (KMeans)')
    plt.savefig(f"img/img-retouched/img-{x}-retouched/img-{x}-retouched-{z}.jpg")
    plt.close()
    
    print("각 클러스터의 면적(픽셀 수):", cluster_areas)
    print("클러스터 중심 색상 (RGB):", centers)
    
    data = {'cluster_id': [], 'rgb_color': [], 'area_pixels': []}
    
    for i in range(n):
        data['cluster_id'].append(f'Cluster {i}')
        data['rgb_color'].append(tuple(centers[i]))
        data['area_pixels'].append(cluster_areas[i])
        
    df = pandas.DataFrame(data)
    df.to_csv(f"retouched-data/retouched-data-{x}-{z}.csv", index=False)
    print(f"클러스터 면적 정보가 저장되었습니다.")
    
    return cluster_areas, segmented_image

In [14]:
for i in range(1, 6):
    Kmeans_color_segment(f"img/img-resized/img-{i}-resized.jpg", 2, i, 2)
    Kmeans_color_segment(f"img/img-resized/img-{i}-resized.jpg", 3, i, 3)
    Kmeans_color_segment(f"img/img-resized/img-{i}-resized.jpg", 4, i, 4)

C:\Users\katia\AppData\Local\Temp\ipykernel_17992\598248360.py:20: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(5754031), 1: np.int64(4485969)}
클러스터 중심 색상 (RGB): [[ 82 188 160]
 [ 27  74  61]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_17992\598248360.py:20: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(2810652), 1: np.int64(3747681), 2: np.int64(3681667)}
클러스터 중심 색상 (RGB): [[ 16  50  42]
 [ 95 205 178]
 [ 52 136 112]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_17992\598248360.py:20: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(3219549), 1: np.int64(2327330), 2: np.int64(2879447), 3: np.int64(1813674)}
클러스터 중심 색상 (RGB): [[ 62 184 151]
 [ 12  43  35]
 [ 49 114  96]
 [124 215 193]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_17992\598248360.py:20: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(3984331), 1: np.int64(6255669)}
클러스터 중심 색상 (RGB): [[ 60  91  82]
 [129 178 155]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_17992\598248360.py:20: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(2370190), 1: np.int64(4666955), 2: np.int64(3202855)}
클러스터 중심 색상 (RGB): [[ 46  70  66]
 [139 187 164]
 [ 90 137 118]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_17992\598248360.py:20: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(2527757), 1: np.int64(1877277), 2: np.int64(3450528), 3: np.int64(2384438)}
클러스터 중심 색상 (RGB): [[100 169 143]
 [ 41  64  60]
 [150 189 167]
 [ 83 115 104]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_17992\598248360.py:20: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(4927107), 1: np.int64(5312893)}
클러스터 중심 색상 (RGB): [[124 184 169]
 [ 45  71  63]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_17992\598248360.py:20: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(3810641), 1: np.int64(3482193), 2: np.int64(2947166)}
클러스터 중심 색상 (RGB): [[ 34  56  49]
 [ 87 133 122]
 [142 207 192]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_17992\598248360.py:20: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(2697958), 1: np.int64(2759222), 2: np.int64(2148603), 3: np.int64(2634217)}
클러스터 중심 색상 (RGB): [[101 161 146]
 [ 25  46  39]
 [152 215 201]
 [ 68  99  90]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_17992\598248360.py:20: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(4920579), 1: np.int64(5319421)}
클러스터 중심 색상 (RGB): [[ 32  84  72]
 [ 87 184 167]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_17992\598248360.py:20: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(3967644), 1: np.int64(3561773), 2: np.int64(2710583)}
클러스터 중심 색상 (RGB): [[ 55 133 113]
 [ 98 199 184]
 [ 20  56  50]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_17992\598248360.py:20: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(3660277), 1: np.int64(2544387), 2: np.int64(2566518), 3: np.int64(1468818)}
클러스터 중심 색상 (RGB): [[ 56 127 107]
 [ 18  53  48]
 [ 61 192 175]
 [144 201 187]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_17992\598248360.py:20: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(5528720), 1: np.int64(4711280)}
클러스터 중심 색상 (RGB): [[ 67  80  81]
 [119 183 177]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_17992\598248360.py:20: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(3840745), 1: np.int64(3295023), 2: np.int64(3104232)}
클러스터 중심 색상 (RGB): [[ 96 127 122]
 [ 51  61  63]
 [126 201 196]]
클러스터 면적 정보가 저장되었습니다.


C:\Users\katia\AppData\Local\Temp\ipykernel_17992\598248360.py:20: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


각 클러스터의 면적(픽셀 수): {0: np.int64(2630791), 1: np.int64(2013430), 2: np.int64(3217356), 3: np.int64(2378423)}
클러스터 중심 색상 (RGB): [[103 156 146]
 [ 36  48  51]
 [ 85  96  96]
 [132 208 206]]
클러스터 면적 정보가 저장되었습니다.
